#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("People2Orgs.Resource", IsApplication=true)]

namespace People2Orgs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int C10 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int C100 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int C25 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int C50 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int C80 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int C90 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int enviar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Listo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Listo2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int monoandroidsplash = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rojo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int verde = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int btnRetroalimentacion = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int calificacion = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int ibAumentar = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ibRestar = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int ibtnEnviar = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int imageButton2 = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int imgExpresion = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int pregunta = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int relativeLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tvSaludo = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Retroalimentacion = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Retroalimentar = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
